steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/ankit-playground-449806/flask-app/flask', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/ankit-playground-449806/flask-app/flask']
# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --image=us-central1-docker.pkg.dev/ankit-playground-449806/flask-app/flask
  - --location=us-central1
  - --cluster=alpha
images:
- us-central1-docker.pkg.dev/ankit-playground-449806/flask-app/flask
options:
  logging: CLOUD_LOGGING_ONLY