apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: nginx
    env: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      env: green
  template:
    metadata:
      labels:
        app: nginx
        env: green
    spec:
      containers:
      - name: nginx
        image: ankitsarkar31/test-app:v1
        ports:
        - containerPort: 8080